AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: INVALID_PROTOCOL
          Endpoint: test@example.com
  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: memory-alarm
      MetricName: MemoryUtilization
      Namespace: CWAgent
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref MyTopic]