AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /app/production
      RetentionInDays: 999
  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: error-rate
      MetricName: ErrorCount
      Namespace: MyApp
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref MyTopic]