AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
  MyQueue:
    Type: AWS::SQS::Queue
  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: queue-depth
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions: [!Ref MyTopic]