AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: INVALID_MFA
      UsernameAttributes: [INVALID_ATTR]
  MyClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyUserPool
      ExplicitAuthFlows: [INVALID_FLOW]
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-api
      EndpointConfiguration:
        Types: [INVALID_TYPE]