AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: 'OFF'
      UsernameAttributes: [email]
  MyClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyUserPool
      ExplicitAuthFlows: [ALLOW_USER_PASSWORD_AUTH, ALLOW_REFRESH_TOKEN_AUTH]
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: secure-api
  MyStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref MyApi
      StageName: INVALID STAGE NAME