AWSTemplateFormatVersion: '2010-09-09'
Description: Complex - IAM + CloudWatch + SNS errors
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: INVALID_EFFECT
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: my-alarm
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: INVALID_STAT
      Period: 99999
      EvaluationPeriods: 0
      Threshold: 80
      ComparisonOperator: INVALID_OP
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: my-topic
      Subscription:
        - Protocol: INVALID_PROTOCOL
          Endpoint: test@example.com