AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
  MyTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: worker-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !GetAtt MyRole.Arn
      ContainerDefinitions:
        - Name: worker
          Image: worker:latest
          Memory: 1024
          Essential: true
  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDef
      LaunchType: FARGATE
      DesiredCount: 99999