AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
  MyTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: api-task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt MyRole.Arn
      ContainerDefinitions:
        - Name: api
          Image: python:3.9
          Memory: 512
          Essential: true
          LogConfiguration:
            LogDriver: INVALID_LOG_DRIVER