AWSTemplateFormatVersion: '2010-09-09'
Description: ElastiCache - Invalid engine + node type
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
  MySubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: My subnet group
      SubnetIds: [!Ref MySubnet]
  MyCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.invalid.type
      Engine: INVALID_ENGINE
      NumCacheNodes: 0
      CacheSubnetGroupName: !Ref MySubnetGroup