AWSTemplateFormatVersion: '2010-09-09'
Description: IAM - Invalid instance profile
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: INVALID_PATH_FORMAT
      Roles: [!Ref MyRole]