AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineType: INVALID_TYPE
      RoleArn: !GetAtt MyRole.Arn
      DefinitionString: |
        {"StartAt":"Start","States":{"Start":{"Type":"INVALID_STATE","End":true}}}