AWSTemplateFormatVersion: '2010-09-09'
Description: IAM + S3 bucket policy - Invalid action
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-valid-bucket-iam-test
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: INVALID_ACTION
            Resource: !Sub 'arn:aws:s3:::${MyBucket}/*'