AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: INVALID_ACL
  MyStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 2