AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: INVALID$$BUCKET###NAME
  MyStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 0
      StreamModeDetails:
        StreamMode: INVALID_MODE
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
  MyFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: INVALID_TYPE
      S3DestinationConfiguration:
        BucketARN: !GetAtt MyBucket.Arn
        CompressionFormat: INVALID_FORMAT
        RoleARN: !GetAtt MyRole.Arn