AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda - Invalid architecture
Resources:
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python3.9
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Architectures: [INVALID_ARCH]
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello'