AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + Lambda - Invalid bucket name
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: My_Invalid_Bucket$$$$
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python3.9
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello'