AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + Lambda - Invalid handler
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-valid-bucket-005
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python3.9
      Handler: 12345
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello'