AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + Lambda - Invalid bucket name + runtime
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: INVALID_BUCKET_NAME!!!
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: ruby1.0
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello'