AWSTemplateFormatVersion: '2010-09-09'
Description: S3 + Lambda - Multiple errors
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: INVALID$$BUCKET
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python1.0
      Handler: index.handler
      MemorySize: 55555
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        ZipFile: |
          def handler(event, context):
            return 'Hello'