AWSTemplateFormatVersion: '2010-09-09'
Description: SQS - Invalid retention period
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue
      MessageRetentionPeriod: 9999999