AWSTemplateFormatVersion: '2010-09-09'
Description: SQS - Invalid visibility timeout
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue
      VisibilityTimeout: 99999