AWSTemplateFormatVersion: '2010-09-09'
Description: SQS + SNS - Missing topic ref
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: my-queue
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref NonExistentTopic
      Protocol: email
      Endpoint: test@example.com