AWSTemplateFormatVersion: '2010-09-09'
Description: VPC + EC2 + SG - Wrong AZ
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-9a
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My SG
      VpcId: !Ref MyVPC
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet
      SecurityGroupIds: [!Ref MySG]