AWSTemplateFormatVersion: '2010-09-09'
Description: VPC + EC2 - Invalid AMI
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-99999999
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet