AWSTemplateFormatVersion: '2010-09-09'
Description: VPC + EC2 - Hardcoded AZ + Invalid AMI
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-south-9a
  MySubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ap-south-9b
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-11111111
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet1