AWSTemplateFormatVersion: '2010-09-09'
Description: VPC + EC2 - Missing SubnetId ref
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      SubnetId: !Ref NonExistentSubnet